GET http://localhost:8000/api/v1/horarios

GET http://localhost:8000/api/v1/horarios?filters=semestre:1,ano:2018

GET http://localhost:8000/api/v1/horarios/22

POST http://localhost:8000/api/v1/horarios
Content-Type: application/json

{
    "descricao": "Primeiro ensalamento de teste para o segundo semestere",
    "ano": 2017,
    "semestre": 2
}

PUT http://localhost:8000/api/v1/horarios/1
Content-Type: application/json

{
    "descricao": "Nova descrição"
}

DELETE http://localhost:8000/api/v1/horarios/2